import = [
  "~/.config/alacritty/themes/gruvbox_dark.toml"  
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

startup_mode = "Fullscreen"

[font]
normal.family = "MesloLGS NF"
size = 19
